/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['body[_ngcontent-%COMP%]{\n  background-color: #F0BD67 ;\n  border : solid #000000 1px;\n  border-radius : 8px;\n}\n\nh3[_ngcontent-%COMP%]{\n  font-family : "Permanent Marker";\n  margin-left : 10px;\n  font-size : 2em;\n}\n\np[_ngcontent-%COMP%]{\n  margin-left : 10px;\n  font-family : "Concert One";\n  font-size : 1.5em;\n  display: inline;\n}\n\n\n#h3current[_ngcontent-%COMP%] {\n\n}\n\nmeter[_ngcontent-%COMP%] {\n  \n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWxleGFuZHJlL0Rlc2t0b3AvdGFza19hcHAvbXktYXBwL3NyYy9hcHAvY3VycmVudF9kaXNwbGF5LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9hbGV4YW5kcmUvRGVza3RvcC90YXNrX2FwcC9teS1hcHAvc3JjL2FwcC9jdXJyZW50X2Rpc3BsYXkuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
