/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['h1[_ngcontent-%COMP%] {\n  font-family: "Bungee";\n	color : #ffffff;\n	margin-left: 0.2em;\n	display: inline-block;\n	text-align : justify;\n}\n\nheader[_ngcontent-%COMP%] {\n	background-color : #5E412F;\n	width: 100%;\n}\n\nbody[_ngcontent-%COMP%]{\n  background-color : #FCEBB6;\n}\n\n@font-face{\n	font-family: "Permanent Marker";\n	src: url(PermanentMarker-Regular.ttf);\n}\n\n@font-face{\n	font-family: "Bungee";\n	src : url(Bungee-Regular.ttf);\n}\n\n@font-face{\n	font-family: "Concert One";\n	src : url(ConcertOne-Regular.ttf);\n}\n\nselect[_ngcontent-%COMP%] {\n	display: inline-block;\n	border: 0 !important;\n	background-color: #ffffff;\n	width: 100%;\n}\n\n.select[_ngcontent-%COMP%] {\n	display: inline-block;\n	vertical-align: baseline;\n	width: 15%;\n	right: 0;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWxleGFuZHJlL0Rlc2t0b3AvdGFza19hcHAvbXktYXBwL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9hbGV4YW5kcmUvRGVza3RvcC90YXNrX2FwcC9teS1hcHAvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
