/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.module';
import * as i2 from '../../../src/app/app.component';
import * as i3 from './list_display.component.ngfactory';
import * as i4 from './app.component.ngfactory';
import * as i5 from '@angular/common';
import * as i6 from '@angular/platform-browser';
import * as i7 from '@angular/forms';
import * as i8 from 'angular-in-memory-web-api/interfaces';
import * as i9 from '../../../src/app/in-memory-data.service';
import * as i10 from '@angular/http';
import * as i11 from 'angular-in-memory-web-api/http-in-memory-web-api.module';
import * as i12 from '@angular/common/http';
import * as i13 from 'angular-in-memory-web-api/http-client-in-memory-web-api.module';
import * as i14 from '@angular/router';
import * as i15 from '@ngx-translate/core/src/translate.loader';
import * as i16 from '@ngx-translate/core/src/translate.compiler';
import * as i17 from '@ngx-translate/core/src/translate.parser';
import * as i18 from '@ngx-translate/core/src/missing-translation-handler';
import * as i19 from '../../../src/app/missing-translation';
import * as i20 from '@ngx-translate/core/src/translate.store';
import * as i21 from '@ngx-translate/core/src/translate.service';
import * as i22 from '../../../src/app/task.service';
import * as i23 from 'angular-in-memory-web-api/in-memory-web-api.module';
import * as i24 from '../../../src/app/list_display.component';
import * as i25 from '../../../src/app/app-routing.module';
import * as i26 from '@ngx-translate/core/index';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.ListDisplayComponentNgFactory,i4.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i5.NgLocalization,i5.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,
              i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,
              ([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i6.DomSanitizer,i6.ɵe,[i5.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i6.DomSanitizer]),i0.ɵmpd(4608,i6.HAMMER_GESTURE_CONFIG,
              i6.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,i6.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i6.ɵDomEventsPlugin(p0_0),new i6.ɵKeyEventsPlugin(p1_0),
                    new i6.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i5.DOCUMENT,i5.DOCUMENT,i5.DOCUMENT,i6.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i6.EventManager,i6.EventManager,[i6.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i6.ɵDomSharedStylesHost,i6.ɵDomSharedStylesHost,[i5.DOCUMENT]),
          i0.ɵmpd(4608,i6.ɵDomRendererFactory2,i6.ɵDomRendererFactory2,[i6.EventManager,
              i6.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i6.ɵDomRendererFactory2]),i0.ɵmpd(6144,i6.ɵSharedStylesHost,(null as any),
              [i6.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i6.Meta,i6.Meta,[i5.DOCUMENT]),i0.ɵmpd(4608,
              i6.Title,i6.Title,[i5.DOCUMENT]),i0.ɵmpd(4608,i7.ɵi,i7.ɵi,([] as any[])),
          i0.ɵmpd(4608,i8.InMemoryDbService,i9.InMemoryDataService,([] as any[])),
          i0.ɵmpd(5120,i10.XHRBackend,i11.httpInMemBackendServiceFactory,[i0.Injector,
              i8.InMemoryDbService,i8.InMemoryBackendConfig]),i0.ɵmpd(4608,i10.RequestOptions,
              i10.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i10.Http,i10.ɵc,[i10.XHRBackend,
              i10.RequestOptions]),i0.ɵmpd(4608,i10.BrowserXhr,i10.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i10.ResponseOptions,i10.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i10.XSRFStrategy,i10.ɵb,([] as any[])),i0.ɵmpd(4608,i12.HttpXsrfTokenExtractor,
              i12.ɵg,[i5.DOCUMENT,i0.PLATFORM_ID,i12.ɵe]),i0.ɵmpd(4608,i12.ɵh,i12.ɵh,
              [i12.HttpXsrfTokenExtractor,i12.ɵf]),i0.ɵmpd(5120,i12.HTTP_INTERCEPTORS,
              (p0_0:any) => {
                return [p0_0];
              },[i12.ɵh]),i0.ɵmpd(4608,i12.ɵd,i12.ɵd,([] as any[])),i0.ɵmpd(6144,i12.XhrFactory,
              (null as any),[i12.ɵd]),i0.ɵmpd(5120,i12.HttpBackend,i13.httpClientInMemBackendServiceFactory,
              [i8.InMemoryDbService,i8.InMemoryBackendConfig,i12.XhrFactory]),i0.ɵmpd(5120,
              i12.HttpHandler,i12.ɵinterceptingHandler,[i12.HttpBackend,[2,i12.HTTP_INTERCEPTORS]]),
          i0.ɵmpd(4608,i12.HttpClient,i12.HttpClient,[i12.HttpHandler]),i0.ɵmpd(4608,
              i12.HttpXhrBackend,i12.HttpXhrBackend,[i12.XhrFactory]),i0.ɵmpd(5120,
              i14.ActivatedRoute,i14.ɵf,[i14.Router]),i0.ɵmpd(4608,i14.NoPreloading,
              i14.NoPreloading,([] as any[])),i0.ɵmpd(6144,i14.PreloadingStrategy,
              (null as any),[i14.NoPreloading]),i0.ɵmpd(135680,i14.RouterPreloader,
              i14.RouterPreloader,[i14.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i14.PreloadingStrategy]),i0.ɵmpd(4608,i14.PreloadAllModules,
              i14.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i14.ROUTER_INITIALIZER,
              i14.ɵi,[i14.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i14.ROUTER_INITIALIZER]),i0.ɵmpd(5120,i15.TranslateLoader,i1.HttpLoaderFactory,
              [i12.HttpClient]),i0.ɵmpd(4608,i16.TranslateCompiler,i16.TranslateFakeCompiler,
              ([] as any[])),i0.ɵmpd(4608,i17.TranslateParser,i17.TranslateDefaultParser,
              ([] as any[])),i0.ɵmpd(4608,i18.MissingTranslationHandler,i19.NanoTaskMissingTranslationHandler,
              ([] as any[])),i0.ɵmpd(4608,i20.TranslateStore,i20.TranslateStore,([] as any[])),
          i0.ɵmpd(4608,i21.TranslateService,i21.TranslateService,[i20.TranslateStore,
              i15.TranslateLoader,i16.TranslateCompiler,i17.TranslateParser,i18.MissingTranslationHandler,
              i21.USE_DEFAULT_LANG,i21.USE_STORE]),i0.ɵmpd(4608,i22.TaskService,i22.TaskService,
              [i10.Http]),i0.ɵmpd(512,i5.CommonModule,i5.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i6.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i14.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i14.ɵg,i14.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i6.ɵc(p0_0,p0_1),i14.ɵh(p1_0)];
              },[[2,i6.NgProbeToken],[2,i0.NgProbeToken],i14.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i6.BrowserModule,i6.BrowserModule,[[3,i6.BrowserModule]]),i0.ɵmpd(512,
              i7.ɵba,i7.ɵba,([] as any[])),i0.ɵmpd(512,i7.FormsModule,i7.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i10.HttpModule,i10.HttpModule,([] as any[])),
          i0.ɵmpd(512,i12.HttpClientXsrfModule,i12.HttpClientXsrfModule,([] as any[])),
          i0.ɵmpd(512,i12.HttpClientModule,i12.HttpClientModule,([] as any[])),i0.ɵmpd(512,
              i23.InMemoryWebApiModule,i23.InMemoryWebApiModule,([] as any[])),i0.ɵmpd(1024,
              i14.ɵa,i14.ɵd,[[3,i14.Router]]),i0.ɵmpd(512,i14.UrlSerializer,i14.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i14.ChildrenOutletContexts,i14.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i14.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i5.LocationStrategy,i14.ɵc,[i5.PlatformLocation,[2,i5.APP_BASE_HREF],
              i14.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i5.Location,i5.Location,[i5.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i14.ROUTES,() => {
            return [[{path:'',redirectTo:'/list_display',pathMatch:'full'},{path:'list_display',
                component:i24.ListDisplayComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i14.Router,i14.ɵe,[i0.ApplicationRef,i14.UrlSerializer,
              i14.ChildrenOutletContexts,i5.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i14.ROUTES,i14.ROUTER_CONFIGURATION,[2,i14.UrlHandlingStrategy],
              [2,i14.RouteReuseStrategy]]),i0.ɵmpd(512,i14.RouterModule,i14.RouterModule,
              [[2,i14.ɵa],[2,i14.Router]]),i0.ɵmpd(512,i25.AppRoutingModule,i25.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i26.TranslateModule,i26.TranslateModule,([] as any[])),
          i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),i0.ɵmpd(256,i8.InMemoryBackendConfig,
              {passThruUnknownUrl:true},([] as any[])),i0.ɵmpd(256,i12.ɵe,'XSRF-TOKEN',
              ([] as any[])),i0.ɵmpd(256,i12.ɵf,'X-XSRF-TOKEN',([] as any[])),i0.ɵmpd(256,
              i21.USE_STORE,(undefined as any),([] as any[])),i0.ɵmpd(256,i21.USE_DEFAULT_LANG,
              (undefined as any),([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWxleGFuZHJlL0Rlc2t0b3AvdGFza19hcHAvbXktYXBwL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2FsZXhhbmRyZS9EZXNrdG9wL3Rhc2tfYXBwL215LWFwcC9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
